In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Economics.pdf
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/ReadMe.pdf
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/TheAutomators/LabAnalysis.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/TheAutomators/GreenhouseClimate.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/TheAutomators/GrodanSens.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/TheAutomators/CropParameters.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/TheAutomators/Production.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/TheAutomators/Resources.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/TheAutomators/TomQuality.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Automatoes/LabAnalysis.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Automatoes/GreenhouseClimate.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Automatoes/GrodanSens.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Automatoes/CropParameters.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Automatoes/Production.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Automatoes/Resources.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Automatoes/TomQuality.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/IUACAAS/LabAnalysis.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/IUACAAS/GreenhouseClimate.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/IUACAAS/GrodanSens.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/IUACAAS/CropParameters.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/IUACAAS/Production.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/IUACAAS/Resources.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/IUACAAS/TomQuality.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Reference/LabAnalysis.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Reference/GreenhouseClimate.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Reference/GrodanSens.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Reference/CropParameters.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Reference/Production.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Reference/Resources.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Reference/TomQuality.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Weather/Weather.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/AICU/LabAnalysis.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/AICU/GreenhouseClimate.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/AICU/GrodanSens.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/AICU/CropParameters.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/AICU/Production.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/AICU/Resources.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/AICU/TomQuality.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Digilog/LabAnalysis.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Digilog/GreenhouseClimate.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Digilog/GrodanSens.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Digilog/CropParameters.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Digilog/Production.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Digilog/Resources.csv
/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/Digilog/TomQuality.csv

## Merge Data

The input data currently contains multiple csv files 
To merge, we backfill (fill NaN with the next value in the col) the columns with lesser entries and create a df for each team.

In [28]:
# create dataframe for each dataset of all teams

teams = ["Digilog","AICU","IUACAAS","Automatoes","TheAutomators"]
datasets = ["LabAnalysis.csv","GreenhouseClimate.csv","GrodanSens.csv","CropParameters.csv","Production.csv","Resources.csv","TomQuality.csv",]

df_raw = []
df_teams  = []
i = 0
for i in range(len(teams)):
    df_raw.append([])
    for data in datasets:
        df_tmp = pd.read_csv("/kaggle/input/autonomous-greenhouse-challengeagc-2nd-2019/{}/{}".format(teams[i],data))
        df_tmp = df_tmp.rename(columns={"%Time":"%time","%Time ":"%time"}) # rename Time col to have the same name "%time"
        df_raw[i].append(df_tmp)
    
    df_team = pd.concat(df_raw[i],sort=True)  # merge all the datasets
    df_team = df_team.fillna(method="bfill")  # bfill all na fields
    
    
    # TODO: ffill the values after bfill 
    
    df_teams.append(df_team)

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3156: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,14,15,17,18,20,22,23,25,27,29,31,33,35,37,39,41,43,44,45,47,49) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [30]:
df_teams[0]

,%Juice,%time,Acid,AssimLight,Bite,BlackScr,CO2_cons,CO2air,Cum_irr,Cum_trusses,...,t_slab1,t_slab2,t_vent_sp,t_ventlee_vip,t_ventwind_vip,water_sup,water_sup_intervals_sp_min,water_sup_intervals_vip_min,window_pos_lee_sp,window_pos_lee_vip
0,68.0,43836.0,13.3,0,193.0,35,0.006253,474,0.2,1.0,...,NaN,NaN,NaN,25.0,26.0,2.0,NaN,1000,NaN,1.2
1,68.0,43850.0,13.3,0,193.0,35,0.006253,474,0.2,1.0,...,NaN,NaN,NaN,25.0,26.0,2.0,NaN,1000,NaN,1.2
2,68.0,43864.0,13.3,0,193.0,35,0.006253,474,0.2,1.0,...,NaN,NaN,NaN,25.0,26.0,2.0,NaN,1000,NaN,1.2
3,68.0,43879.0,13.3,0,193.0,35,0.006253,474,0.2,1.0,...,NaN,NaN,NaN,25.0,26.0,2.0,NaN,1000,NaN,1.2
4,68.0,43893.0,13.3,0,193.0,35,0.006253,474,0.2,1.0,...,NaN,NaN,NaN,25.0,26.0,2.0,NaN,1000,NaN,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,60.0,43922.0,14.9,NaN,263.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,55.0,43936.0,14.0,NaN,298.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,68.0,43950.0,12.6,NaN,190.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,69.0,43964.0,12.4,NaN,148.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,57.0,43980.0,9.6,NaN,182.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
# save the merged team csv file
for i in range(len(df_teams)):
    df_teams[i].to_csv("Team {}.csv".format(i))